services:
  stt:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-stt
    networks: !override
      - juno-net
    container_name: juno-stt
  stt-stream:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-stt-stream
    networks: !override
      - juno-net
    container_name: juno-stt-stream
  stt-stream-rust:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-stt-stream-rust
    networks: !override
      - juno-net
    container_name: juno-stt-stream-rust
  llm:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-llm
    networks: !override
      - juno-net
    container_name: juno-llm
  tts:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-tts
    networks: !override
      - juno-net
    container_name: juno-tts
  monitor:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-monitor
    networks: !override
      - juno-net
    container_name: juno-monitor
  llm-gemma3-4b:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-llm-gemma3-4b
    networks: !override
      - juno-net
    container_name: juno-llm-gemma3-4b
  llm-embedding:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-llm-embedding
    networks: !override
      - juno-net
    container_name: juno-llm-embedding
  memory:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-memory
    networks: !override
      - juno-net
    container_name: juno-memory
  llm-gemma3-4b:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-llm-gemma3-4b
    networks: !override
      - juno-net
    container_name: juno-llm-gemma3-4b
  llm-embedding:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-llm-embedding
    networks: !override
      - juno-net
    container_name: juno-llm-embedding
  cli:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-cli
    networks: !override
      - juno-net
    container_name: juno-cli
  test-playback:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-test-playback
    networks: !override
      - juno-net
    container_name: juno-test-playback
  message-broker:
    build: !reset
    image: ghcr.io/juno-ai-labs/juno-message-broker
    networks: !override
      - juno-net
    container_name: juno-message-broker
  setup-ipc:
    networks: !override
      - juno-net
    container_name: juno-ipc-setup

networks:
  juno-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
